name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    env:
      Solution_Name: Veri.Framework.sln                        # Replace with your solution name, i.e. MyWpfApp.sln.


    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Add MSBuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1

    # Add Nuget
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.5

    # Restore the Nuget packages
    - name: Restore NuGet Packages
      run: nuget restore $env:Solution_Name

    # Restore solution
    - name: Restore Solution
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=Release

    # Build and publish app
    - name: Build and Publish Web App
      run: msbuild $env:Solution_Name /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile

    # Build and publish app
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        name: published_application
        path: publish